version: '3.8'

services:
  animedownloader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: animedownloader
    ports:
      - "${PORT}:3000"
    environment:
      - NODE_ENV=production
      - DOCKER=true
      - anidbUser=${anidbUser}
      - anidbPassword=${anidbPassword}
    volumes:
      # Configure the animeLocation in the app to use /app/downloads
      - ./anime:/app/anime
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/quarter"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

